export const loremIpsumSegments = [
  `
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mattis dolor orci, ut condimentum lectus commodo nec. Phasellus tincidunt enim vitae orci interdum, quis rhoncus libero euismod. Etiam at sagittis arcu. Sed euismod, arcu lacinia semper gravida, elit dui maximus elit, vitae lobortis nisl dolor id mi. Mauris faucibus interdum dui vel accumsan. Suspendisse et arcu ut ex egestas vestibulum sit amet at urna. Quisque condimentum, justo quis porttitor placerat, purus dui faucibus magna, sit amet condimentum ante diam id lorem. Sed at ipsum non elit tincidunt facilisis. Curabitur vel ornare turpis. Fusce non consectetur velit. Duis tellus massa, pulvinar a rutrum quis, tincidunt imperdiet metus. Mauris interdum dui eget nisl imperdiet tristique. Cras sodales turpis ut enim luctus vestibulum. Suspendisse sit amet dui bibendum, efficitur ante quis, aliquet libero.`,

`Sed ligula nunc, tempor in arcu id, scelerisque fermentum ante. Cras congue libero eget orci ultrices, ut condimentum sem lobortis. Sed aliquet, arcu in ornare tincidunt, metus arcu rhoncus metus, aliquam convallis nisl elit sed nibh. Etiam at aliquam purus. Vivamus tincidunt fringilla cursus. Ut et lobortis nulla. Maecenas eget nulla id eros sollicitudin efficitur nec ac nisl. Aenean ut tortor et arcu mattis ultricies. Sed vel mauris egestas tortor laoreet scelerisque at a nibh. Phasellus vehicula vel purus sit amet dictum. Maecenas luctus, metus a tincidunt mollis, turpis nibh vulputate risus, bibendum ultricies dui purus ut augue. Cras at mauris non mi porttitor pharetra ac vitae tortor.`,

`Nunc vitae odio felis. Etiam ultrices venenatis porta. Proin tellus leo, sagittis semper nunc ac, sodales porttitor neque. Phasellus pharetra mi eget accumsan dapibus. In porta ultrices elit nec varius. Aenean convallis quam massa, eget mattis metus molestie id. Maecenas bibendum convallis odio, ut iaculis mi faucibus ac. Suspendisse ac rhoncus lorem. In vestibulum imperdiet ex. Suspendisse nec dignissim eros. In libero leo, cursus sed auctor quis, rhoncus sodales libero.`,

`Nullam varius mauris quis iaculis luctus. Pellentesque mattis tortor felis, sit amet lacinia eros scelerisque eu. Maecenas vulputate eleifend ipsum. Nunc faucibus eu lacus sed mattis. Cras a elit sit amet elit tincidunt dignissim. Suspendisse lobortis arcu urna, ut vehicula libero dictum non. Donec vitae vulputate mi, ut commodo diam.`,

`Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla maximus lectus id augue luctus vehicula. Donec fringilla feugiat consequat. Mauris euismod augue a varius aliquam. Nullam vestibulum urna sit amet ex malesuada laoreet. Suspendisse malesuada vehicula hendrerit. Nunc lacus est, aliquet at lorem non, tristique luctus nunc. Pellentesque at augue nulla. Praesent mollis lectus quis dapibus molestie. Phasellus ornare rutrum diam, nec fringilla libero malesuada ac. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec venenatis malesuada mauris et congue. Curabitur eu eleifend eros, quis facilisis urna. Phasellus sollicitudin massa ac volutpat mollis.`,

`Donec et est ut enim sagittis posuere id a sapien. Morbi id ante ut ante auctor vehicula. Nam vel sodales leo. Nullam eu risus at felis mattis auctor. Integer neque massa, bibendum a commodo eu, varius a nibh. Ut in tempus leo. Pellentesque sit amet tempus arcu. Maecenas non dui in purus consequat fringilla ut id metus. Praesent in cursus augue. Integer ultricies facilisis sapien, non vestibulum quam rhoncus euismod. Sed maximus eros non libero fringilla, vel faucibus turpis dictum. Sed malesuada vitae justo sed malesuada. Praesent ut ligula imperdiet nulla fermentum interdum. Vivamus mattis fringilla quam nec feugiat. Nam vulputate velit odio.`,

`Nunc tempus enim cursus, facilisis mauris ut, laoreet eros. Vestibulum est diam, interdum in volutpat at, molestie ut lacus. Duis vehicula velit sed aliquam tristique. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin sed volutpat neque. Sed leo tellus, condimentum sed neque non, aliquet vulputate est. Vestibulum egestas vulputate ligula sit amet scelerisque. Suspendisse libero est, tincidunt nec orci nec, pretium laoreet libero.`,

`Etiam facilisis vitae risus ut imperdiet. Suspendisse potenti. Aliquam sit amet risus in neque imperdiet hendrerit. Cras euismod eros ut pulvinar tempus. Aenean et purus mi. Nullam luctus, felis a dictum consequat, est elit pulvinar augue, et ornare dolor sapien imperdiet est. Nam lacinia bibendum hendrerit. In orci libero, aliquet eget scelerisque nec, ornare dapibus lectus. Ut elementum nisi vitae mauris lobortis, sit amet tristique nibh maximus. Aenean pellentesque, eros in vehicula dictum, leo elit venenatis mauris, eget porttitor nunc libero ut metus. Praesent at est quis dui condimentum lobortis ut vel leo. Cras ut lacus a dui mattis luctus. Donec id tristique augue. Fusce ut mi ornare purus tempor malesuada sit amet vitae elit. Phasellus luctus ultrices nunc vitae pharetra. Nulla vehicula, velit non dictum fringilla, leo quam ornare ante, eu volutpat metus augue id tellus.`,

`Donec dapibus laoreet nunc, ut ultrices est imperdiet ut. Pellentesque consectetur purus varius, ornare enim a, pretium dui. Quisque velit dolor, hendrerit sit amet enim bibendum, interdum faucibus ante. Fusce porttitor blandit risus eget hendrerit. Suspendisse et dolor auctor, auctor urna id, cursus nunc. Phasellus sit amet magna nec purus pharetra lacinia vitae id lorem. Donec condimentum lectus a nunc fringilla, iaculis viverra justo efficitur. Quisque consequat nulla leo, iaculis hendrerit purus ullamcorper ac.`,

`Nullam semper, elit ut dignissim finibus, nulla felis ornare nunc, eu bibendum odio leo nec diam. Fusce blandit eros et nisi vulputate ultricies. Fusce sit amet ligula varius, gravida magna vel, vehicula sem. Morbi a venenatis eros. Curabitur efficitur tortor quis quam maximus, tincidunt pharetra turpis tempus. Praesent auctor eleifend lectus, eu accumsan felis ultrices id. Morbi blandit, tellus in ullamcorper tincidunt, lorem nisl bibendum diam, nec euismod lectus lorem eget ante. Nunc finibus ultricies bibendum. Maecenas convallis imperdiet odio, ac venenatis tellus tincidunt quis. In id nibh sit amet eros vulputate suscipit.`,

`Nunc risus nulla, dictum a consequat et, blandit at nisi. Pellentesque ac mauris justo. Praesent convallis purus dolor, scelerisque placerat libero porttitor in. Sed ut tristique diam, nec efficitur nisl. Donec tempor porta velit non sagittis. In interdum vehicula leo id posuere. Praesent ultricies leo feugiat felis euismod, sit amet hendrerit libero tristique. Suspendisse vel erat turpis. Donec auctor sem dolor, sit amet lacinia dolor dictum id.`,

`Maecenas et purus suscipit, scelerisque neque sed, sollicitudin elit. Sed venenatis nisl quis risus euismod sollicitudin. Aliquam vel convallis urna. Pellentesque velit quam, aliquet quis pellentesque id, laoreet ut lectus. Aenean commodo magna libero, eleifend sagittis lacus iaculis at. Nam orci lorem, porttitor non urna eu, tempor auctor mi. Curabitur lobortis faucibus leo, ac luctus ipsum tempus ut. Cras quis accumsan enim. Quisque ornare finibus iaculis. Duis ut velit ac justo ultrices molestie in sed purus. Duis mollis maximus mi sed sollicitudin. Praesent molestie eros at pulvinar convallis. Phasellus justo nulla, ullamcorper eget blandit ut, malesuada at risus. Duis vel dapibus felis. Pellentesque eget lacinia est, eu dapibus tortor. Phasellus eu felis ligula.`,

`Sed et diam suscipit, commodo metus vitae, ultrices nibh. Nam et nulla facilisis, lobortis est at, condimentum nunc. Integer erat dui, egestas id est sed, elementum sagittis nisl. Aenean sed enim rutrum, porttitor est eget, ullamcorper ante. Maecenas aliquet urna in porta rhoncus. Aenean volutpat commodo sapien, vel mattis tortor rutrum consequat. Integer egestas est non lacus pretium, et tincidunt nulla tristique. Nunc volutpat nisl commodo risus posuere rutrum. Vestibulum dapibus sodales magna nec feugiat. Pellentesque id posuere nunc.`,

`Sed id interdum sapien. Donec auctor feugiat magna, at lacinia nibh molestie placerat. Vestibulum et quam velit. Proin ultricies vitae odio ac blandit. In tristique placerat bibendum. Phasellus dui mi, pretium sed ligula non, luctus tincidunt justo. Maecenas ornare nulla ac ultricies bibendum.`,

`Sed leo nulla, euismod eu elit sit amet, dignissim consequat justo. Nulla pulvinar lacus at turpis vulputate tristique. Sed imperdiet lacus ac mi malesuada, vitae sollicitudin quam posuere. Phasellus erat leo, facilisis nec viverra a, pharetra et tortor. Etiam eget ultrices nisl, a placerat mauris. In eu sem ut orci dictum hendrerit. Ut vitae sem luctus, laoreet massa eget, dignissim erat. Quisque tellus nulla, pulvinar a augue ut, mattis convallis nibh. Phasellus diam velit, dictum vitae lacinia vel, porttitor ut odio. Donec sed ex nulla. In vel metus faucibus, accumsan nisl ac, varius lacus.`,

`Nulla rhoncus eleifend orci. Sed congue eleifend varius. Cras sed massa sapien. Donec consectetur tristique turpis, at semper augue vulputate in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras accumsan sed turpis sed auctor. In rutrum est ut blandit auctor. Etiam porta lacinia odio a semper. In lacinia velit sem, ac dignissim mi scelerisque id. Nam sit amet diam id lorem dictum placerat.`,

`Integer ultrices orci id metus bibendum, at pulvinar felis porttitor. Suspendisse potenti. Phasellus vitae ipsum dictum, sodales dolor vitae, semper ex. Ut luctus felis urna, id varius sapien euismod efficitur. Cras elementum est quis rhoncus accumsan. Quisque eget augue nec arcu venenatis finibus. Vestibulum ornare auctor vehicula. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ex urna, blandit pellentesque tortor et, dignissim aliquet nisi. Donec lacus mi, feugiat eu consequat quis, pellentesque vel dui. Maecenas mollis est dolor, sit amet varius tellus posuere eget. Nam at lacinia ex. Nulla eu velit urna.`,

`Proin vulputate sem vitae ligula placerat, vitae commodo lorem eleifend. In in rutrum purus. Nam convallis neque pretium arcu condimentum, vel ornare odio porttitor. Phasellus tincidunt, lacus ac tincidunt faucibus, nunc elit lobortis tellus, nec tincidunt justo urna ut ex. Nullam accumsan elit dignissim felis vulputate, eget eleifend sapien aliquam. Vestibulum convallis sodales sagittis. Duis nec magna ac arcu varius imperdiet. Nullam eu sapien odio. Curabitur egestas lobortis interdum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nunc condimentum risus vitae bibendum volutpat. Donec eleifend urna in erat sagittis blandit.`,

`Morbi viverra, dui vestibulum interdum sollicitudin, dui velit porttitor diam, ac posuere nisl est in lorem. Phasellus venenatis molestie finibus. Maecenas nec tempus ante, ut faucibus orci. Nullam nec condimentum ligula. Ut interdum nisi et tortor mattis posuere. Vivamus accumsan tincidunt ex, rhoncus consectetur nisl varius sit amet. Aenean elementum consectetur quam, non varius leo tristique et. Suspendisse in tempor felis. Pellentesque enim odio, iaculis sed felis vel, ultrices viverra metus. Vivamus sapien ipsum, congue a nunc at, posuere gravida leo. Nam ut metus scelerisque tellus accumsan commodo in consectetur est. Proin pharetra et dui et rutrum.`,

`Phasellus risus urna, imperdiet eu libero vitae, facilisis blandit eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tincidunt, lectus in pellentesque facilisis, nunc purus congue risus, eget semper ipsum ligula nec dolor. In convallis lacus at mauris posuere, sed vulputate dolor accumsan. Praesent sagittis elit nisl, ultricies interdum erat interdum eget. Morbi porttitor interdum mi, eu ultricies arcu scelerisque sed. Donec ullamcorper ornare libero quis consectetur. Sed ut sapien quis sem volutpat tincidunt. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec eget rutrum mauris, et blandit nibh. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.`,
];
